# Generated by Django 4.2.7 on 2023-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('uniform', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=32)),
                ('allies', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('advancement', models.CharField(max_length=256)),
                ('ability', models.TextField()),
                ('instinct', models.CharField(max_length=32)),
                ('rotation', models.JSONField(blank=True, null=True)),
                ('PvE', models.BooleanField(default=False)),
                ('PvP', models.BooleanField(default=False)),
                ('Dealer', models.BooleanField(default=False)),
                ('Leader', models.BooleanField(default=False)),
                ('Support', models.BooleanField(default=False)),
                ('leadership', models.JSONField(null=True)),
                ('support_buff', models.JSONField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='character')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterCTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CTPs', to='character.character')),
                ('custom_gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ctp.ctp')),
            ],
        ),
    ]
