# Generated by Django 4.2.7 on 2023-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exclusive_skill', models.CharField(max_length=128)),
                ('PvE_score', models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], max_length=1)),
                ('PvP_score', models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High')], max_length=1)),
                ('rank_3', models.TextField()),
                ('rank_4', models.TextField()),
                ('rank_5', models.TextField()),
                ('rank_6', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifact/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='character.character')),
            ],
        ),
    ]
