# Generated by Django 4.2.7 on 2023-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('stat_1', models.TextField()),
                ('stat_2', models.TextField()),
                ('stat_3', models.TextField()),
                ('stat_4', models.TextField()),
                ('stat_5', models.TextField()),
                ('stat_6', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='card/')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
