# Generated by Django 4.2.7 on 2023-11-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('r', 'Regular'), ('m', 'Mighty'), ('b', 'Brilliant')], max_length=1)),
                ('description', models.TextField()),
                ('reforged_description', models.TextField()),
                ('max_stats', models.TextField()),
                ('reforged_option_1', models.TextField(blank=True, null=True)),
                ('reforged_option_2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ctp/')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
